# Generated by Django 3.2.3 on 2021-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0009_auto_20210601_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
